name: applejuice-collector
title: appleJuice Collector
summary: appleJuice Collector for appleJuice Client
description: appleJuice Collector for appleJuice Client
icon: snap/gui/applejuice-collector.png
version: 3.1.0
license: MIT

grade: stable
confinement: strict
base: core22

architectures:
  - build-on: amd64
  - build-on: arm64

layout:
  /usr/bin/xprop:
    bind-file: $SNAP/usr/bin/xprop

hooks:
  configure:
    plugs: [ home ]

apps:
  collector:
    command: $SNAP/app/launcher
    extensions:
      - gnome
    environment:
      AJ_COLLECTOR_DISABLE_UPDATE_CHECK: "yes"
      JAVA_HOME: $SNAP/usr/lib/jvm/java-21-openjdk-$SNAP_ARCH
      PATH: $JAVA_HOME/bin:$PATH
    plugs:
      - home
      - desktop
      - network
      - x11

  service:
    command: $SNAP/app/launcher
    daemon: simple
    install-mode: disable
    environment:
      JAVA_HOME: $SNAP/usr/lib/jvm/java-21-openjdk-$SNAP_ARCH
      PATH: $JAVA_HOME/bin:$PATH
    plugs:
      - home
      - network

parts:
  collector:
    plugin: nil
    override-pull: wget -P $SNAPCRAFT_PART_INSTALL https://github.com/applejuicenetz/core-information-collector/releases/download/$SNAPCRAFT_PROJECT_VERSION/AJCollector.jar
    build-packages:
      - wget
    organize:
      'AJCollector.jar': app/

  jre:
    plugin: nil
    build-packages:
      - ca-certificates
      - ca-certificates-java
      - openjdk-21-jre
    stage-packages:
      - openjdk-21-jre
      - x11-utils
    override-prime: |
      snapcraftctl prime
      rm -vf usr/lib/jvm/java-21-openjdk-*/lib/security/blacklisted.certs

  launcher:
    plugin: dump
    source: ./snap/local/
    organize:
      '*': $SNAP/app/
