name: applejuice-collector
title: appleJuice Collector
summary: appleJuice Collector for appleJuice Client
description: appleJuice Collector for appleJuice Client
version: 3.0.0
icon: snap/gui/applejuice-collector.png
license: MIT
grade: stable
confinement: strict
base: core18
architectures:
  - build-on: amd64
  - build-on: i386
  - build-on: armhf
  - build-on: arm64
layout:
  /usr/bin/xprop:
    bind-file: $SNAP/usr/bin/xprop
apps:
  collector:
    command: $SNAP/app/launcher
    extensions:
      - gnome-3-28
    environment:
      AJ_COLLECTOR_DISABLE_UPDATE_CHECK: yes
      JAVA_HOME: $SNAP/usr/lib/jvm/java-11-openjdk-$SNAP_ARCH
      PATH: $JAVA_HOME/bin:$PATH
    plugs:
      - home
      - desktop
      - desktop-legacy
      - network
      - x11
parts:
  collector:
    plugin: nil
    override-pull: wget -P $SNAPCRAFT_PART_INSTALL https://github.com/applejuicenetz/core-information-collector/releases/download/$SNAPCRAFT_PROJECT_VERSION/AJCollector.jar
    build-packages:
      - wget
    organize:
      'AJCollector.jar': app/
  jre:
    plugin: nil
    build-packages:
      - ca-certificates
      - ca-certificates-java
      - openjdk-11-jre
    stage-packages:
      - openjdk-11-jre
      - x11-utils
  launcher:
    plugin: dump
    source: ./snap/local
    organize:
      '*': app/
