name: ci

on:
  pull_request:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: read
  packages: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: actions/setup-java@v6
        with:
          distribution: zulu
          java-version: '25'
          cache: maven
          server-id: github
          server-username-env-var: GITHUB_ACTOR
          server-password-env-var: GITHUB_TOKEN
      - name: Build and test
        env:
          GITHUB_TOKEN: ${{ github.token }}
        run: mvn -B package
