name: 'docker'

on:
  workflow_dispatch:
  schedule:
    - cron: '0 7 * * MON'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Inject slug/short variables
        uses: rlespinasse/github-slug-action@v2.x

      - name: Get build time
        uses: 1466587594/get-current-time@v1
        id: current-time

      - name: Login to ghcr.io
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ secrets.GHCR_USER }}
          password: ${{ secrets.GHCR_TOKEN }}

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USER }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          platforms: linux/amd64,linux/arm64,linux/386,linux/arm
          push: true
          build-args: |
            BUILD_DATE=${{ steps.current-time.outputs.time }}
            VCS_REF=${{ env.GITHUB_SHA_SHORT }}
          tags: |
            ghcr.io/${{ github.repository }}:latest
            ${{ github.repository }}:latest
