name: 'snapcraft'

on:
  release:
    types: [ released ]

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set Snapcraft Version
        uses: mikefarah/yq@master
        with:
          cmd: yq eval -i '.version = "${{ github.ref_name }}"' 'snap/snapcraft.yaml'

      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          file_pattern: snap/snapcraft.yaml
          branch: master
          commit_message: Update snapcraft package to ${{ github.ref_name }}
